version: 2.1

jobs:
  sparse-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip install -U pytest
      - run: pytest tests.py

  build-and-push-docker-image:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t paramsangani/my-python-app:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$kzrzvzX7f_!%g4!" | docker login -u "$paramsangani" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push paramsangani/my-python-app:latest

workflows:
  version: 2
  sparse-test-and-push-image:
    jobs:
      - sparse-test
      - build-and-push-docker-image:
          filters:
            branches:
              only:
                - main
