version: 2.1

jobs:
  sparse-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip install -U pytest
      - run: pytest tests.py

  build-and-push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            SHORT_SHA1=$(echo "${CIRCLE_SHA1}" | cut -c 1-7)
            docker build -t paramsangani/myapp:${SHORT_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$kzrzvzX7f_!%g4!" | docker login --username "$paramsangani" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            SHORT_SHA1=$(echo "${CIRCLE_SHA1}" | cut -c 1-7)
            docker push $paramsangani/myapp:${SHORT_SHA1}


workflows:
  version: 2
  sparse-test:
    jobs:
      - sparse-test
      - build-and-push:
          filters:
            branches:
              only:
                - main
